manifest:
  version: "1.0"

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.7.0
      import:
        file: west.yml
        name-allowlist:
          - cmsis
          - hal_nordic
          - nrfxlib
          - tinycrypt

  self:
    path: manifest
